
topic:
  redis:
    channelInfoAccount: account-info
    channelErrorAccount: account-error

  kafka:
    blockFundsTopic: block-funds-topic
    clearingPaymentTopic: clearing-payment-topic
    cancelPaymentTopic: cancel-payment-topic
    authorizationTopic: authorization-topic
    responseAuthorisationTopic: response-authorisation-topic
    responseCancelTopic: response-cancel-topic
    responseClearingTopic: response-clearing-topic

kafka:
  partitions:
    paymentRequest: payment-request
    paymentResponse: payment-response

batch:
  box:
    size: 30
    volume: 500

cron:
  cashback: '0 0 2 3 * *'
  operation:
    free:
      account:
        number: '0 */30 * * * *'


logging:
  level:
    com:
      example:
        account_service: DEBUG
    org:
      springframework:
        data:
          redis: DEBUG

size:
  max_account_from_owner: 15
