user-login:
  username: admin
  password: admin123

topic:
  redis:
    channelInfoAccount: account-info
    channelErrorAccount: account-error

  kafka:
    blockFundsTopic: block-funds-topic
    confirmPaymentTopic: confirm-payment-topic
    cancelPaymentTopic: cancel-payment-topic
    authorizationTopic: authorization-topic

kafka:
  partitions:
    paymentRequest: payment-request
    paymentResponse: payment-response

batch:
  box:
    size: 10
    volume: 500

cron:
  operation:
    free:
      account:
        number: '0 */30 * * * *'


logging:
  level:
    com:
      example:
        account_service: DEBUG
    org:
      springframework:
        data:
          redis: DEBUG
