user-login:
  username: admin
  password: admin123

topic:
  redis:
    channelInfoAccount: account-info
    channelErrorAccount: account-error

  kafka:
    channelInfo: account-info

batch:
  box:
    size: 10

cron:
  operation:
    free:
      account:
        number: '0 */30 * * * *'