spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache:
          use_query_cache:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      port: 6379
      host: localhost
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 10000

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: record
      concurrency: 3
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.fasterxml.jackson.databind.JsonSerializer
    producer:
      properties:
        acks: all
        batch.size: 16384
        linger.ms: 5
        retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.fasterxml.jackson.databind.JsonSerializer


  profiles:
    active: data, dev

server:
  port: 8088

async:
  pools:
    worker: Async-worker-

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: api/docs

